### ISSUE TITLE
< and > are displayed as html entity codes

### ISSUE THREAD

**Issue by gnaomo** [itshichabk/mkds-wiimmfi-dashboard#2]
username: **< githubmk>** was set on the firmware settings, could be other glyphs beside "<" and ">" 

###  wiimmfi.de
![Screenshot 2024-10-05 154036](https://github.com/user-attachments/assets/0305dc55-0073-4de8-9d12-6a07da8b04b6)
___
### itshichabks's API
![Screenshot 2024-10-05 154126](https://github.com/user-attachments/assets/a73adb16-fa78-4175-bcb8-76d0a10db25d)
___
### mkds-wiimmfi-dashboard
![Screenshot 2024-10-05 154100](https://github.com/user-attachments/assets/32ccba58-87e0-426f-a3e4-7e6b1e0de760)

**Comment by itshichabk** [comment]
Looks like a HTML issue, pretty sure it does that on purpose to prevent script injections. I'll look into it

**Comment by itshichabk** [comment]
And done!
